name: easacc_flutter_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

      # Network
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  # Routing
  go_router: ^17.0.0

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency injection
  get_it: ^8.2.0

  # UI & UX
  icons_launcher: ^3.0.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  modal_progress_hud_nsn: ^0.5.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  flutter_spinkit: ^5.2.2
  
  # Internationalization & formatting
  intl: ^0.20.2

  # Functional & utilities
  dartz: ^0.10.1

  # Local storage
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  # Device discovery
  multicast_dns: ^0.3.3
  flutter_blue_plus: ^2.0.2
  network_info_plus: ^7.0.0
  permission_handler: ^12.0.1

  # Social authentication
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/svgs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
          style: normal


flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart



icons_launcher:
  image_path: "assets/images/easacc_logo.jpeg"

  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_intl:
  enabled: true

dependency_overrides:
  permission_handler: 12.0.1
  permission_handler_android: 13.0.1
